name: pokedx
description: A Pokedex experience with Flutter.

publish_to: "none"

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  cached_network_image: ^3.3.0
  firebase_analytics: ^10.6.4
  firebase_core: ^2.22.0
  firebase_crashlytics: ^3.4.4
  firebase_performance: ^0.9.3+4
  firebase_remote_config: ^4.3.4

  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.3
  flutter_native_splash: ^2.3.5

  http: ^1.1.0

dev_dependencies:
  bloc_test: ^9.1.5
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^3.0.1

  flutter_test:
    sdk: flutter

  mocktail: ^1.0.1

flutter:
  uses-material-design: true
  assets:
    - images/
    - images/types/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/pokedex.png"
  min_sdk_android: 22
  remove_alpha_ios: true
  background_color_ios: "#303030"
  web:
    generate: true
    image_path: "images/pokedex.png"
    background_color: "#303030"
    theme_color: "#424242"

flutter_native_splash:
  color: "#303030"
  fullscreen: true
  image: images/pokedex.png
